Inventory/ViewModels/PurchaseReceiveViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Inventory.Domain;

namespace Inventory.WebUI
{
    public class DirectPurchaseReceiveViewModel
    {

        public int Id { get;set; }

        [Required]
        [Display(Name = "Purchase No")]
        public string PurchaseNo { get; set; }

        [Required]
        public int SupplierId { get; set; }

        [Required]
        [Display(Name = "Receive as")]
        public ReceivedStockTypeEnum ReceivedStockType { get; set; }

        [Required]
        public DateTime ReceiveDate { get; set; }

        public string Remarks { get; set; }
    }

    //public class PurchaseReceiveItemViewModel
    //{
    //    public long Id { get; set; }

    //    public int index { get; set; }

    //    [Required]
    //    public long ItemId { get; set; }

    //    [Required]
    //    public long UnitOfMeasureId { get; set; }

    //    [Required]
    //    public long ItemQty { get; set; }

    //    public string ItemName { get; set; }

    //    public string UnitName { get; set; }
    //    public decimal ConversionFactor { get; set; }

    //}

    public class ItemComboViewModel
    {
        public long ItemId { get; set; }

        public string ItemName { get; set; }
    }
}

Inventory/Controllers/PurchaseReceiveController.cs
using System.IO;
using Inventory.Domain;
using Inventory.WebUI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;

namespace Inventory.Controllers
{
    [Authorize]
    public class PurchaseReceiveController : Controller
    {
        private IUnitOfWork unitOfWork;


        public PurchaseReceiveController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: /PurchaseReceive/
        public ActionResult DirectPurchase()
        {
            List<PurchaseReceive> rcvList = new List<PurchaseReceive>();
            rcvList = unitOfWork
                        .PurchaseReceiveRepository
                        .GetPurchaseReceives()
                        .Where(x => x.PurchaseOrderID == null && x.ReceiveDate == DateTime.Today).ToList();



            rcvList.ForEach(x => x.TotalAmount = x.PurchaseReceiveItems.Sum(item => item.Price));

            return View(rcvList);
        }

        public ActionResult FilterDirectPurchases(string receivedStockType, DateTime? fromDate, DateTime? toDate)
        {
            ViewBag.FromDate = fromDate;
            ViewBag.ToDate = toDate;

            List<PurchaseReceive> rcvList = new List<PurchaseReceive>();
            if (!string.IsNullOrEmpty(receivedStockType) && fromDate.HasValue && toDate.HasValue)
            {
                ReceivedStockTypeEnum rsType = (ReceivedStockTypeEnum)Convert.ToInt32(receivedStockType);
                rcvList = unitOfWork
                .PurchaseReceiveRepository
                .GetPurchaseReceives()
                .Where(x => x.PurchaseOrderID == null && x.ReceivedStockType == rsType && (x.ReceiveDate >= fromDate.Value && x.ReceiveDate <= toDate.Value)).ToList();
            }
            else if (string.IsNullOrEmpty(receivedStockType) && fromDate.HasValue && toDate.HasValue)
            {
                //ReceivedStockTypeEnum rsType = (ReceivedStockTypeEnum)Convert.ToInt32(receivedStockType);
                rcvList = unitOfWork
                .PurchaseReceiveRepository
                .GetPurchaseReceives()
                .Where(x => x.PurchaseOrderID == null && (x.ReceiveDate >= fromDate.Value && x.ReceiveDate <= toDate.Value)).ToList();
            }
            else
            {
                rcvList = unitOfWork
                    .PurchaseReceiveRepository
                    .GetPurchaseReceives()
                    .Where(x => x.PurchaseOrderID == null).ToList();
            }

            rcvList.ForEach(x => x.TotalAmount = x.PurchaseReceiveItems.Sum(item => item.Price));

            ViewBag.ReceivedStocks = rcvList;
            //return PartialView("EditorTemplates/PurchaseReceive", ViewBag.ReceivedStocks);
            return PartialView("PurchaseReceiveGridPartial", ViewBag.ReceivedStocks);
        }

        [HttpPost]
        public ActionResult Report(IList<PurchaseReceive> purchaseReceives)
        {
            string ids = string.Empty;
            foreach (var purchaseReceive in purchaseReceives.Where(x => x.IsSelected))
            {
                ids += purchaseReceive.Id.ToString() + ',';
            }
            ids = ids.Trim(',');

            LocalReport lr = new LocalReport();
            string path = Path.Combine(Server.MapPath("~/Report"), "PurchaseReceiveInvoiceReport.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return PartialView("PurchaseReceiveGridPartial");
            }

            InventoryDataSet InDataSet = new InventoryDataSet();

            InventoryDataSetTableAdapters.PurchaseReceiveInvoiceReportTableAdapter InTableAdapter =
                new InventoryDataSetTableAdapters.PurchaseReceiveInvoiceReportTableAdapter();

            InTableAdapter.Fill(InDataSet.PurchaseReceiveInvoiceReport, ids);

            ReportDataSource rd = new ReportDataSource("PurchaseReceiveInvoiceReport", InDataSet.Tables["PurchaseReceiveInvoiceReport"]);
            lr.DataSources.Add(rd);
            const string reportType = "PDF";
            string mimeType;
            string encoding;
            string fileNameExtention;

            const string deviceInfo =
                    "<DeviceInfo>" +
                    "<OutputFormat>" + reportType + "</OutputFormat>" +
                    "<PageWidth>8.5in</PageWidth>" +
                    "<PageHeight>11in</PageHeight>" +
                    "<MarginTop>0.5in</MarginTop>" +
                    "<MarginLeft>1in</MarginLeft>" +
                    "<MarginRight>1in</MarginRight>" +
                    "<MarginBottom>0.5in</MarginBottom>" +
                    "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;

            byte[] renderredBytes = lr.Render(reportType,
                deviceInfo,
                out mimeType,
                out encoding,
                out fileNameExtention,
                out streams,
                out warnings);


            return File(renderredBytes, mimeType);
        }

        public ActionResult Report(string id)
        {
            string ids = string.IsNullOrEmpty(id) ? string.Empty : id.Trim(',');
            

            LocalReport lr = new LocalReport();
            string path = Path.Combine(Server.MapPath("~/Report"), "PurchaseReceiveInvoiceReport.rdlc");
            if (System.IO.File.Exists(path))
            {
                lr.ReportPath = path;
            }
            else
            {
                return PartialView("PurchaseReceiveGridPartial");
            }

            InventoryDataSet InDataSet = new InventoryDataSet();

            InventoryDataSetTableAdapters.PurchaseReceiveInvoiceReportTableAdapter InTableAdapter =
                new InventoryDataSetTableAdapters.PurchaseReceiveInvoiceReportTableAdapter();

            if (ids != string.Empty)
                InTableAdapter.Fill(InDataSet.PurchaseReceiveInvoiceReport, ids);

            ReportDataSource rd = new ReportDataSource("PurchaseReceiveInvoiceReport", InDataSet.Tables["PurchaseReceiveInvoiceReport"]);
            lr.DataSources.Add(rd);
            const string reportType = "PDF";
            string mimeType;
            string encoding;
            string fileNameExtention;

            const string deviceInfo =
                    "<DeviceInfo>" +
                    "<OutputFormat>" + reportType + "</OutputFormat>" +
                    "<PageWidth>8.5in</PageWidth>" +
                    "<PageHeight>11in</PageHeight>" +
                    "<MarginTop>0.5in</MarginTop>" +
                    "<MarginLeft>1in</MarginLeft>" +
                    "<MarginRight>1in</MarginRight>" +
                    "<MarginBottom>0.5in</MarginBottom>" +
                    "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;

            byte[] renderredBytes = lr.Render(reportType,
                deviceInfo,
                out mimeType,
                out encoding,
                out fileNameExtention,
                out streams,
                out warnings);


            return File(renderredBytes, mimeType);
        }

        public ActionResult DetailsDirectPurchase(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchaseReceive pReceive = unitOfWork.PurchaseReceiveRepository.GetPurchaseByID(id.Value);

            if (pReceive == null)
            {
                return HttpNotFound();
            }

            List<Item> ItemList = unitOfWork.ItemRepository.GetItems(string.Empty).ToList();
            List<UnitOfMeasure> UOMList = unitOfWork.UnitOfMeasureRepository.GetUnitOfMeasures().ToList();

            int count = 1;
            foreach (var item in pReceive.PurchaseReceiveItems)
            {
                item.index = count++;
                item.ItemName = ItemList.First(x => x.Id == item.Stock.ItemId).Name;
                item.UnitName = UOMList.First(x => x.Id == item.UnitOfMeasureId).Name;
            }

            ViewBag.PurchaseReceiveItems = pReceive.PurchaseReceiveItems.ToList();

            return View(pReceive);
        }
        public ActionResult CreateDirectPurchase()
        {
            DirectPurchaseReceiveViewModel VModel = new DirectPurchaseReceiveViewModel();

            ViewBag.Suppliers = new SelectList(unitOfWork.SupplierRepository.GetSuppliers().ToList(), "Id", "Name", VModel.SupplierId);

            ViewBag.Items = unitOfWork.ItemRepository.GetItems(string.Empty).Select(x => new ItemComboViewModel() { ItemId = x.Id, ItemName = x.Name });

            Session["PurchaseReceiveItems"] = ViewBag.PurchaseReceiveItems = new List<PurchaseReceiveItem>();

            // = new List<PurchaseReceiveItem>();

            return View(VModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDirectPurchase(DirectPurchaseReceiveViewModel VModel)
        {
            if (ModelState.IsValid)
            {
                //DirectPurchaseReceiveViewModel VModel = new DirectPurchaseReceiveViewModel();
                try
                {
                    PurchaseReceive PurchaseReceive = new PurchaseReceive()
                    {
                        PurchaseNo = VModel.PurchaseNo,
                        SupplierId = VModel.SupplierId,
                        ReceiveDate = VModel.ReceiveDate,
                        ReceivedStockType = VModel.ReceivedStockType,
                        Remarks = VModel.Remarks

Inventory/Views/PurchaseReceive/DeleteDirectPurchase.cshtml
@model Inventory.Domain.PurchaseReceive

@{
    ViewBag.Title = "Delete Received Stock";
}

<h2>Delete Received Stock</h2>


<div>
    <h3>Are you sure about deleting this Received Stock?</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PurchaseNo) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.Name) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiveDate) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiveDate)
        </dd>
        <dt>
            Received as :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceivedStockType)
        </dd>

    </dl>
    <br />

    <div class="row clearfix">
        <h4>Items List:</h4>
        <br />
        <div class="col-md-6 column">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Item
                        </th>
                        <th align="right">
                            Quantity
                        </th>
                        <th>
                            Messuring Unit
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="items-table-body">
                    @foreach (var item in ViewBag.PurchaseReceiveItems as List<Inventory.Domain.PurchaseReceiveItem>)
                    {
                        <tr>
                            <td> @item.index </td>
                            <td> @item.ItemName </td>
                            <td align="right"> @item.ItemQty </td>
                            <td> @item.UnitName </td>
                        </tr>
                    }
                </tbody>

            </table>
            <hr />
        </div>
        <div class="col-md-6 column">


        </div>

    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "DirectPurchase")
        </div>
    }
</div>

Inventory/Views/PurchaseReceive/DetailsDirectPurchase.cshtml
@model Inventory.Domain.PurchaseReceive

@{
    ViewBag.Title = "Details Received Stock";
}



<div>
    <h2>Details of Received Stock</h2>
    
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PurchaseNo) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.Name) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiveDate) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiveDate)
        </dd>
        
        <dt>
            Received as :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceivedStockType)
        </dd>

    </dl>
    <br />

    <div class="row clearfix">
        <h4>Items List:</h4>
        <br />
        <div class="col-md-6 column">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Item
                        </th>
                        <th align="right">
                            Quantity
                        </th>
                        <th>
                            Messuring Unit
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="items-table-body">
                    @foreach (var item in ViewBag.PurchaseReceiveItems as List<Inventory.Domain.PurchaseReceiveItem>)
                    {
                        <tr>
                            <td> @item.index </td>
                            <td> @item.ItemName </td>
                            <td align="right"> @item.ItemQty </td>
                            <td> @item.UnitName </td>
                        </tr>
                    }
                </tbody>

            </table>
            <hr />
        </div>
        <div class="col-md-6 column">
            
            
        </div>

    </div>

</div>
<br />
<p>
    @Html.ActionLink("Edit", "UpdateDirectPurchase", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "DirectPurchase")
</p>

Inventory/Views/PurchaseReceive/DirectPurchase.cshtml
@using Inventory.Domain
@using Inventory.WebUI
@model IEnumerable<Inventory.Domain.PurchaseReceive>

@{
    ViewBag.Title = "Stock Receive";
    List<PurchaseReceive> oReceivedStocks = ViewBag.ReceivedStocks;
}

<h2>Stock Receive</h2>

<p>
    @Html.ActionLink("Create New", "CreateDirectPurchase")
</p>
<div>
    @using (Ajax.BeginForm("FilterDirectPurchases", "PurchaseReceive", new AjaxOptions()
                {
                    UpdateTargetId = "purchaseView",
                    HttpMethod = "Get",
                    OnSuccess = "onSuccess"
                }))
    {
        <div>
            @{Html.RenderPartial("_DateTimeFilteringPartial", new DateTimeViewModel());}
        </div>
        <table>
            <tr>
                <td>
                    <div>
                        <table>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label id="lblReceivedStock" for="ReceivedStockType" class="col-md-2 control-label">Received as</label>
                                    </div>
                                </td>
                                <td>
                                    <div class="form-group">
                                        <div class="col-md-10">
                                            @Html.DropDownList("ReceivedStockType", new SelectList(Enum.GetValues(typeof(ReceivedStockTypeEnum)).Cast<ReceivedStockTypeEnum>().Select(x => new SelectListItem() { Text = x.ToString(), Value = ((int)x).ToString() }), "Value", "Text"), "---Show All---", new
                                            {
                                                @class = "form-control",
                                                @id = "receivedStockType"
                                            })
                                        </div>
                                    </div>
                                </td>
                                <td><input id="btnSubmit" type="submit" value="Search" /></td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    }

</div>

<br />
<table></table>
<br />
    @*@Html.Partial("PurchaseReceiveGridPartial", oReceivedStocks)*@
    @*@Html.EditorFor("EditorTemplates/PurchaseReceive", oReceivedStocks)*@
    @using (Ajax.BeginForm("Report", "PurchaseReceive", new AjaxOptions(){}))
    {
        @*<input id="btnPrintReport" type="submit" value="Print Report" />*@
        <div><a id="lnkReport" class="btn btn-primary" href="~/PurchaseReceive/Report/" target="_blank">Print Report</a></div>
        <div id="purchaseView">
            @*@Html.EditorForModel()*@
            @Html.Partial("PurchaseReceiveGridPartial", oReceivedStocks)

        </div>
    }<style>
    #receivedStockType {
        width: auto;
    }

    #lblReceivedStock {
        width: auto;
    }
</style>

@section Scripts {

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        var checkedids = [];
        var lnk = $('#lnkReport');
        var lnkbaseUrl = lnk.attr('href');
        console.log('Here');

        CheckedChanged = function (element) {
            console.log('Here');
            var $this = $(element);
            console.log($this);
            var id = $this.data('id');
            console.log(id);
            if ($this.prop("checked")) {
                console.log(id);
                AddID(id);
            } else {
                console.log('unchecked:' + id);
                RemoveID(id);
            }

        }

        AddID = function (id) {

            checkedids.push(id);
            UpdateLink();
        }

        RemoveID = function (id) {
            var index = checkedids.indexOf(id);
            if (index > -1) {
                checkedids.splice(index, 1);
            }
            UpdateLink();
        }

        UpdateLink = function () {
            var lnkHref = lnkbaseUrl;
            $.each(checkedids, function (index, value) {
                lnkHref += value + ',';
            });

            lnk.attr("href", lnkHref);
        }

         @*$('#receivedStockType').change(function (e) {
             //debugger;
             e.preventDefault();
             var url = '@Url.Action("FilterDirectPurchases")';
             $.get(url, { receivedStockType: $(this).val() }, function (result) {
                 //debugger;
                 $('#purchaseView').html(result);
             });
         });*@

         @*$("#btnSubmit").on('click', function (e) {
             debugger;
             e.preventDefault();
             var url = '@Url.Action("FilterDirectPurchases")';
             $.get(url, {
                 receivedStockType: $('#receivedStockType').val(),
                 fromDate: $('dtpFromDate').val(),
                 toDate: $('dtpToDate').val()
             }, function (result) {
                 //debugger;
                 $('#purchaseView').html(result);
             });
         });*@


        function onSuccess(result) {
            //debugger;
            $('#purchaseView').html(result);
        };
    </script>
}





Inventory/Views/PurchaseReceive/PurchaseReceiveGridPartial.cshtml
@model IList<Inventory.Domain.PurchaseReceive>
@*@using (Html.BeginForm("Report", "PurchaseReceive",FormMethod.Post))*@

<table class="table" style="border-color: black">

    <tr style="background: lightgray;">
        <th>
            <span class="hdrTexts">Select for Print</span>
        </th>
        <th>
            <span class="hdrTexts">Receipt No</span>
        </th>
        <th>
            <span class="hdrTexts">Supplier</span>
        </th>
        <th>
            <span class="hdrTexts">Receipt Date</span>
        </th>
        <th>
            <span class="hdrTexts">Total Amount(TK)</span>
        </th>
        <th>
            <span class="hdrTexts">Remarks</span>
        </th>
        <th id="thItems" class="hdrTexts">
            <span>Items</span>
            <table>
                <tr style="background: darkgray">
                    <th>
                        Name
                    </th>
                    <th class="col-UOM">
                        Qty
                    </th>
                    @*<th class="col-UOM">
                            Unit Of Measure
                        </th>*@
                    <th>
                        Price
                    </th>
                </tr>
            </table>
        </th>
        <th></th>
    </tr>
    @for (int i = 0; i < Model.Count(); i++)
    {
        <tr>
            @Html.HiddenFor(modelItem => modelItem[i].Id)

            <td class="tdItems">
                <input data-id="@Model[i].Id" onchange="CheckedChanged(this)" type="checkbox" value="true">
            </td>
            <td class="tdItems">
                @Html.DisplayFor(modelItem => modelItem[i].PurchaseNo)
            </td>
            <td class="tdItems">
                @Html.DisplayFor(modelItem => modelItem[i].Supplier.Name)
            </td>
            <td class="tdItems">
                @Html.DisplayFor(modelItem => modelItem[i].ReceiveDate)
            </td>
            <td class="tdItems">
                @Html.DisplayFor(modelItem => modelItem[i].TotalAmount)
            </td>
            <td class="tdItems">
                @Html.DisplayFor(modelItem => modelItem[i].Remarks)
            </td>
            <td>
                @*<table>
                        @{
                            foreach (var childItem in item.PurchaseReceiveItems)
                            {
                                <tr>
                                    <td class ="tdDataItems">
                                        @Html.DisplayFor(x => childItem.Stock.Item.Name)
                                    </td>
                                    <td class="tdDataItems">
                                        @childItem.ItemQty @childItem.UnitOfMeasure.Name
                                    </td>
                                    <td class="tdDataItems">
                                        @Html.DisplayFor(x => childItem.UnitPrice)
                                    </td>
                                </tr>
                                //@:  @childItem.ItemName @childItem.ItemQty @childItem.Price
                            }
                        }
                    </table>*@
                @Html.EditorFor(modelItem => modelItem[i].PurchaseReceiveItems)
            </td>
            <td class="tdItems">
                @Html.ActionLink("Edit", "UpdateDirectPurchase", new { id = Model[i].Id }) |
                @Html.ActionLink("Details", "DetailsDirectPurchase", new { id = Model[i].Id }) |
                @Html.ActionLink("Delete", "DeleteDirectPurchase", new { id = Model[i].Id })
            </td>
        </tr>
    }
</table>

<style>
    #thItems {
        width: 290px;
        text-align: center;
    }

    .tdItems {
        display: table-cell;
        top: 50%;
        position: relative;
        vertical-align: middle;
        -webkit-transform: translateY(50%);
        -ms-transform: translateY(50%);
        transform: translateY(50%);
    }

    .tdDataItems {
        width: 17%;
    }

    .col-UOM {
        width: 150px;
        text-align: center;
    }

    .hdrTexts {
        vertical-align: middle;
    }
</style>
